"""
generate_daily_report.py

Locates the dated Excel file generated by main.py from the output/ folder
and copies it to the reports/ folder with the standardised filename:

    Daily_Performance_YYYY-MM-DD.xlsx

This file is the input consumed by upload_to_drive.py.

Usage:
    python generate_daily_report.py

Environment variables (optional):
    REPORT_DATE   Override the date in YYYY-MM-DD format (default: today IST).
"""

import os
import shutil
from datetime import datetime, timezone, timedelta

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
OUTPUT_FOLDER = "output"
REPORTS_FOLDER = "reports"


def get_ist_date() -> str:
    """Return today's date in Asia/Kolkata (IST = UTC+5:30) as YYYY-MM-DD."""
    ist_offset = timedelta(hours=5, minutes=30)
    now_ist = datetime.now(timezone.utc) + ist_offset
    return now_ist.strftime("%Y-%m-%d")


def generate_daily_report() -> str:
    """
    Locate today's Excel file from output/ and copy it to reports/ with the
    canonical filename Daily_Performance_YYYY-MM-DD.xlsx.

    Returns:
        Absolute path to the generated report file.

    Raises:
        FileNotFoundError: If the source Excel file is missing.
        RuntimeError:      If the reports/ directory cannot be created.
    """
    # Determine target date (allow override via environment variable)
    report_date = os.getenv("REPORT_DATE") or get_ist_date()
    print(f"Generating daily report for date: {report_date}")

    # Source file produced by main.py: output/YYYY-MM-DD.xlsx
    source_filename = f"{report_date}.xlsx"
    source_path = os.path.join(OUTPUT_FOLDER, source_filename)

    if not os.path.exists(source_path):
        raise FileNotFoundError(
            f"ERROR: Source daily Excel file was not found.\n"
            f"  Expected: {source_path}\n"
            f"  Ensure main.py has run successfully before this script."
        )

    # Destination: reports/Daily_Performance_YYYY-MM-DD.xlsx
    os.makedirs(REPORTS_FOLDER, exist_ok=True)

    dest_filename = f"Daily_Performance_{report_date}.xlsx"
    dest_path = os.path.join(REPORTS_FOLDER, dest_filename)

    shutil.copy2(source_path, dest_path)

    print(f"Daily report ready: {dest_path}")
    return dest_path


if __name__ == "__main__":
    report_path = generate_daily_report()
    print(f"\nReport file: {report_path}")
